slack_signup_url: "https://join.slack.com/t/weaviate/shared_invite/zt-goaoifjr-o8FuVz9b1HLzhlUfyfddhw"
weaviate_cli_version: 2.1.2
python_client_version: 3.3.0
markdown: kramdown
highlighter: none
baseurl: /
kramdown:
    parse_block_html: false
rdiscount extensions: [smart]
exclude:
    - "*.json"
    - "Gemfile*"
    - "*.enc"
    - vendor
    - README.md
    - "*.draft"
    - js-src
    - node_modules
    - webpack.config.js
    - Dockerfile
    - "LICENSE.md"
    - "*.rb"
plugins:
    # - jekyll-redirect-from
    - jekyll-toc
# whitelist:
#     - jekyll-redirect-from
toc:
  max_level: 2
  list_id: table-of-contents
  list_class: list mb-0
  item_class: list-item
###
# SPECIFIC SETTINGS FOR THE DOCS
# ALSO SEE THE README FILE
###
weaviate_version: v1.11.0 # the current and latest version
weaviate_versions: # order the versions how you want them displayed
  "v1.11.0":
    helm_version: 14.2.0 # Helm version for this Weaviate version
  "v1.10.1":
    helm_version: 14.2.0 # Helm version for this Weaviate version
  "v1.9.0":
    helm_version: 14.0.1 # Helm version for this Weaviate version
  "v1.8.0":
    helm_version: 14.0.1 # Helm version for this Weaviate version
  "v1.7.2":
    helm_version: 13.4.0 # Helm version for this Weaviate version
  "v1.6.0":
    helm_version: 13.3.0 # Helm version for this Weaviate version
  "v1.5.2":
    helm_version: 13.3.0 # Helm version for this Weaviate version
  "v1.4.1":
    helm_version: 13.3.0 # Helm version for this Weaviate version
  "v1.3.0":
    helm_version: 13.2.0 # Helm version for this Weaviate version
  "v1.2.1":
    helm_version: 13.0.0 # Helm version for this Weaviate version
  "v1.1.0":
    helm_version: 12.0.0 # Helm version for this Weaviate version
  "v1.0.4":
    helm_version: 12.0.0 # Helm version for this Weaviate version
  "0.23.2":
    helm_version: 11.0.0 # Helm version for this Weaviate version
docs:
    weaviate:
        'v1.11.0':
            - name: Getting started
              folder: getting-started
              header: false
            - name: Architecture
              folder: architecture
              header: false
            - name: Configuration
              folder: configuration
              header: false
            - name: Vector Index (ANN) Plugins
              folder: vector-index-plugins
              header: false
            - name: Modules
              folder: modules
              header: false
            - name: Client libraries & CLI
              folder: client-libraries
              header: false
            - name: Data schema
              folder: data-schema
              header: false
            - name: RESTful API references
              folder: restful-api-references
              header: false
            - name: GraphQL references
              folder: graphql-references
              header: false
            - name: More resources
              folder: more-resources
              header: false
            - name: Tutorials
              folder: tutorials
              header: true
        'v1.10.1':
            - name: Getting started
              folder: getting-started
              header: false
            - name: Architecture
              folder: architecture
              header: false
            - name: Configuration
              folder: configuration
              header: false
            - name: Vector Index (ANN) Plugins
              folder: vector-index-plugins
              header: false
            - name: Modules
              folder: modules
              header: false
            - name: Client libraries & CLI
              folder: client-libraries
              header: false
            - name: Data schema
              folder: data-schema
              header: false
            - name: RESTful API references
              folder: restful-api-references
              header: false
            - name: GraphQL references
              folder: graphql-references
              header: false
            - name: More resources
              folder: more-resources
              header: false
            - name: Tutorials
              folder: tutorials
              header: true
        'v1.9.0':
            - name: Getting started
              folder: getting-started
              header: false
            - name: Architecture
              folder: architecture
              header: false
            - name: Configuration
              folder: configuration
              header: false
            - name: Vector Index (ANN) Plugins
              folder: vector-index-plugins
              header: false
            - name: Modules
              folder: modules
              header: false
            - name: Client libraries & CLI
              folder: client-libraries
              header: false
            - name: Data schema
              folder: data-schema
              header: false
            - name: RESTful API references
              folder: restful-api-references
              header: false
            - name: GraphQL references
              folder: graphql-references
              header: false
            - name: More resources
              folder: more-resources
              header: false
            - name: Tutorials
              folder: tutorials
              header: true
        'v1.8.0':
            - name: Getting started
              folder: getting-started
              header: false
            - name: Architecture
              folder: architecture
              header: false
            - name: Configuration
              folder: configuration
              header: false
            - name: Vector Index (ANN) Plugins
              folder: vector-index-plugins
              header: false
            - name: Modules
              folder: modules
              header: false
            - name: Client libraries & CLI
              folder: client-libraries
              header: false
            - name: Data schema
              folder: data-schema
              header: false
            - name: RESTful API references
              folder: restful-api-references
              header: false
            - name: GraphQL references
              folder: graphql-references
              header: false
            - name: More resources
              folder: more-resources
              header: false
            - name: Tutorials
              folder: tutorials
              header: true
        'v1.7.2':
            - name: Getting started
              folder: getting-started
              header: false
            - name: Architecture
              folder: architecture
              header: false
            - name: Configuration
              folder: configuration
              header: false
            - name: Vector Index (ANN) Plugins
              folder: vector-index-plugins
              header: false
            - name: Modules
              folder: modules
              header: false
            - name: Client libraries & CLI
              folder: client-libraries
              header: false
            - name: Data schema
              folder: data-schema
              header: false
            - name: RESTful API references
              folder: restful-api-references
              header: false
            - name: GraphQL references
              folder: graphql-references
              header: false
            - name: More resources
              folder: more-resources
              header: false
            - name: Tutorials
              folder: tutorials
              header: true
        'v1.6.0':
            - name: Getting started
              folder: getting-started
              header: false
            - name: Architecture
              folder: architecture
              header: false
            - name: Configuration
              folder: configuration
              header: false
            - name: Vector Index (ANN) Plugins
              folder: vector-index-plugins
              header: false
            - name: Modules
              folder: modules
              header: false
            - name: Client libraries & CLI
              folder: client-libraries
              header: false
            - name: Data schema
              folder: data-schema
              header: false
            - name: RESTful API references
              folder: restful-api-references
              header: false
            - name: GraphQL references
              folder: graphql-references
              header: false
            - name: More resources
              folder: more-resources
              header: false
            - name: Tutorials
              folder: tutorials
              header: true
        'v1.5.2':
            - name: Getting started
              folder: getting-started
              header: false
            - name: Architecture
              folder: architecture
              header: false
            - name: Configuration
              folder: configuration
              header: false
            - name: Vector Index (ANN) Plugins
              folder: vector-index-plugins
              header: false
            - name: Modules
              folder: modules
              header: false
            - name: Client libraries & CLI
              folder: client-libraries
              header: false
            - name: Data schema
              folder: data-schema
              header: false
            - name: RESTful API references
              folder: restful-api-references
              header: false
            - name: GraphQL references
              folder: graphql-references
              header: false
            - name: More resources
              folder: more-resources
              header: false
            - name: Tutorials
              folder: tutorials
              header: true
        'v1.4.1':
            - name: Getting started
              folder: getting-started
              header: false
            - name: Architecture
              folder: architecture
              header: false
            - name: Configuration
              folder: configuration
              header: false
            - name: Vector Index (ANN) Plugins
              folder: vector-index-plugins
              header: false
            - name: Modules
              folder: modules
              header: false
            - name: Client libraries & CLI
              folder: client-libraries
              header: false
            - name: Data schema
              folder: data-schema
              header: false
            - name: RESTful API references
              folder: restful-api-references
              header: false
            - name: GraphQL references
              folder: graphql-references
              header: false
            - name: More resources
              folder: more-resources
              header: false
            - name: Tutorials
              folder: tutorials
              header: true
        'v1.3.0':
            - name: Getting started
              folder: getting-started
              header: false
            - name: Configuration
              folder: configuration
              header: false
            - name: Vector Index (ANN) Plugins
              folder: vector-index-plugins
              header: false
            - name: Modules
              folder: modules
              header: false
            - name: Client libraries & CLI
              folder: client-libraries
              header: false
            - name: Data schema
              folder: data-schema
              header: false
            - name: RESTful API references
              folder: restful-api-references
              header: false
            - name: GraphQL references
              folder: graphql-references
              header: false
            - name: More resources
              folder: more-resources
              header: false
            - name: Tutorials
              folder: tutorials
              header: true
        'v1.2.1':
            - name: Getting started
              folder: getting-started
              header: false
            - name: Configuration
              folder: configuration
              header: false
            - name: Vector Index (ANN) Plugins
              folder: vector-index-plugins
              header: false
            - name: Modules
              folder: modules
              header: false
            - name: Client libraries & CLI
              folder: client-libraries
              header: false
            - name: Data schema
              folder: data-schema
              header: false
            - name: RESTful API references
              folder: restful-api-references
              header: false
            - name: GraphQL references
              folder: graphql-references
              header: false
            - name: More resources
              folder: more-resources
              header: false
            - name: Tutorials
              folder: tutorials
              header: true
        'v1.1.0':
            - name: Getting started
              folder: getting-started
              header: false
            - name: Configuration
              folder: configuration
              header: false
            - name: Vector Index Plugins
              folder: vector-index-plugins
              header: false
            - name: Modules
              folder: modules
              header: false
            - name: Client libraries & CLI
              folder: client-libraries
              header: false
            - name: Data schema
              folder: data-schema
              header: false
            - name: RESTful API references
              folder: restful-api-references
              header: false
            - name: GraphQL references
              folder: graphql-references
              header: false
            - name: More resources
              folder: more-resources
              header: false
            - name: Tutorials
              folder: tutorials
              header: true
        'v1.0.4':
            - name: Getting started
              folder: getting-started
              header: false
            - name: Configuration
              folder: configuration
              header: false
            - name: Vector Index Plugins
              folder: vector-index-plugins
              header: false
            - name: Modules
              folder: modules
              header: false
            - name: Client libraries & CLI
              folder: client-libraries
              header: false
            - name: Data schema
              folder: data-schema
              header: false
            - name: RESTful API references
              folder: restful-api-references
              header: false
            - name: GraphQL references
              folder: graphql-references
              header: false
            - name: More resources
              folder: more-resources
              header: false
            - name: Tutorials
              folder: tutorials
              header: true
        '0.23.2':
            - name: Getting started
              folder: getting-started
            - name: Configuration
              folder: configuration
            - name: Client libraries & CLI
              folder: client-libraries
            - name: How-tos
              folder: how-tos
            - name: RESTful API references
              folder: restful-api-references
            - name: GraphQL references
              folder: graphql-references
            - name: More resources
              folder: more-resources
    contributor-guide:
        'v1.10.1':
            - name: Weaviate Core
              folder: weaviate-core
            - name: Weaviate Module System
              folder: weaviate-module-system
            - name: Contextionary
              folder: contextionary
            - name: Weaviate Clients
              folder: weaviate-clients
        'v1.9.0':
            - name: Weaviate Core
              folder: weaviate-core
            - name: Weaviate Module System
              folder: weaviate-module-system
            - name: Contextionary
              folder: contextionary
            - name: Weaviate Clients
              folder: weaviate-clients
        'v1.8.0':
            - name: Weaviate Core
              folder: weaviate-core
            - name: Weaviate Module System
              folder: weaviate-module-system
            - name: Contextionary
              folder: contextionary
            - name: Weaviate Clients
              folder: weaviate-clients
        'v1.7.2':
            - name: Weaviate Core
              folder: weaviate-core
            - name: Weaviate Module System
              folder: weaviate-module-system
            - name: Contextionary
              folder: contextionary
            - name: Weaviate Clients
              folder: weaviate-clients
        'v1.6.0':
            - name: Weaviate Core
              folder: weaviate-core
            - name: Weaviate Module System
              folder: weaviate-module-system
            - name: Contextionary
              folder: contextionary
            - name: Weaviate Clients
              folder: weaviate-clients
        'v1.5.2':
            - name: Weaviate Core
              folder: weaviate-core
            - name: Weaviate Module System
              folder: weaviate-module-system
            - name: Contextionary
              folder: contextionary
            - name: Weaviate Clients
              folder: weaviate-clients
        'v1.4.1':
            - name: Weaviate Core
              folder: weaviate-core
            - name: Weaviate Module System
              folder: weaviate-module-system
            - name: Contextionary
              folder: contextionary
            - name: Weaviate Clients
              folder: weaviate-clients
        'v1.3.0':
            - name: Weaviate Core
              folder: weaviate-core
            - name: Weaviate Module System
              folder: weaviate-module-system
            - name: Contextionary
              folder: contextionary
            - name: Weaviate Clients
              folder: weaviate-clients
        'v1.2.1':
            - name: Weaviate Core
              folder: weaviate-core
            - name: Weaviate Module System
              folder: weaviate-module-system
            - name: Contextionary
              folder: contextionary
            - name: Weaviate Clients
              folder: weaviate-clients
        'v1.1.0':
            - name: Weaviate Core
              folder: weaviate-core
            - name: Weaviate Module System
              folder: weaviate-module-system
            - name: Contextionary
              folder: contextionary
            - name: Weaviate Clients
              folder: weaviate-clients
        'v1.0.4':
            - name: Weaviate Core
              folder: weaviate-core
            - name: Contextionary
              folder: contextionary
            - name: Weaviate Clients
              folder: weaviate-clients
        '0.23.2':
            - name: Weaviate Core
              folder: weaviate-core
            - name: Contextionary
              folder: contextionary
            - name: Weaviate Clients
              folder: weaviate-clients
