slack_signup_url: "https://join.slack.com/t/weaviate/shared_invite/zt-goaoifjr-o8FuVz9b1HLzhlUfyfddhw"
weaviate_cli_version: 2.1.2
python_client_version: 3.8.0
markdown: kramdown
highlighter: none
url: https://weaviate.io
baseurl: /
documentation_call_out: false
kramdown:
  parse_block_html: false
rdiscount extensions: [smart]
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:title.html
exclude:
  - "*.json"
  - Gemfile
  - "*.enc"
  - vendor
  - README.md
  - readme.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - "*.draft"
  - js-src
  - node_modules/
  - webpack.config.js
  - Dockerfile
  - LICENSE.md
  - LICENSE
  - "*.rb"
  - "*.sh"
  - .github/
  - .jekyll-cache
  - readme.md
  - tools/
keep_files:
  - img
plugins:
  - jekyll-redirect-from
  - jekyll-toc
  - jekyll-sitemap
  - jekyll-last-modified-at
last-modified-at:
  date-format: '%d-%b-%y'
whitelist:
  - jekyll-redirect-from
toc:
  max_level: 2
  list_id: table-of-contents
  list_class: list mb-0
  item_class: list-item
###
# SPECIFIC SETTINGS FOR THE DOCS
# ALSO SEE THE README FILE
###
weaviate_version: v1.15.5 # the current and latest version
helm_version: 15.0.0 # Helm version for this Weaviate version
docs:
  weaviate:
    current:
      - name: Core Knowledge
        folder: core-knowledge
        header: false
        breakpointAfter: false
      - name: Getting started
        folder: getting-started
        header: false
        breakpointAfter: true
      # - name: Becoming an expert
      #   folder: becoming-an-expert
      #   header: false
      #   breakpointAfter: true
      - name: Installation
        folder: installation
        header: false
      - name: Configuration
        folder: configuration
        header: false
      - name: Client libraries
        folder: client-libraries
        header: false
        breakpointAfter: true
      - name: Schema
        folder: schema
        header: false
        breakpointAfter: true
      - name: GraphQL references
        folder: graphql-references
        header: false
      - name: RESTful API references
        folder: restful-api-references
        header: false
        breakpointAfter: true
      - name: Modules
        folder: modules
        header: false
        breakpointAfter: true
      - name: Retrievers & Vectorizers
        folder: retriever-vectorizer-modules
        header: true
        nav-parent: Modules
      - name: Readers & Generators
        folder: reader-generator-modules
        header: true
        nav-parent: Modules
      - name: Other Modules
        folder: other-modules
        header: true
        nav-parent: Modules
      - name: Roadmap
        folder: roadmap
        header: false
      - name: Architecture
        folder: architecture
        header: false
      - name: Vector Index (ANN) Plugins
        folder: vector-index-plugins
        header: false
      - name: Benchmarks
        folder: benchmarks
        header: false
        breakpointAfter: true
      - name: Tutorials
        folder: tutorials
        header: false
      - name: More resources
        folder: more-resources
        header: false
  contributor-guide:
    current:
      - name: Weaviate Core
        folder: weaviate-core
      - name: Weaviate Module System
        folder: weaviate-module-system
      - name: Contextionary
        folder: contextionary
      - name: Weaviate Clients
        folder: weaviate-clients
