[[redirects]]
from = "/developers/weaviate/release-notes/older-releases/release_1_*"
to = "https://weaviate.io/blog/weaviate-1-:splat-release"
status = 301

[[redirects]]
from = "/developers/weaviate/release-notes/release_1_*"
to = "https://weaviate.io/blog/weaviate-1-:splat-release"
status = 301

# Redirect all remaining /developers & /docs requests to docs subdomain
[[redirects]]
  from = "/developers/*"
  to = "https://docs.weaviate.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/docs/*"
  to = "https://docs.weaviate.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/blog/chatgpt-for-generative-search"
  to = "https://docs.weaviate.io/weaviate/model-providers/openai/generative"
  status = 301

[[redirects]]
  from = "/collections-count-limit"
  to = "https://docs.weaviate.io/weaviate/starter-guides/managing-collections/collections-scaling-limits"
  status = 301

[[edge_functions]]
function = "block-feed-bot"
path = "/blog/rss.xml"

[[edge_functions]]
function = "block-feed-bot"
path = "/blog/atom.xml"